CREATE PROCEDURE [dbo].st_TestCPU
AS
BEGIN
   ALTER INDEX ALL ON OrdersBig1 REBUILD
   ALTER INDEX ALL ON OrdersBig2 REBUILD
   ALTER INDEX ALL ON OrdersBig3 REBUILD
   ALTER INDEX ALL ON OrdersBig4 REBUILD
   ALTER INDEX ALL ON OrdersBig5 REBUILD
   ALTER INDEX ALL ON OrdersBig6 REBUILD
   ALTER INDEX ALL ON OrdersBig7 REBUILD
   ALTER INDEX ALL ON OrdersBig8 REBUILD
   ALTER INDEX ALL ON OrdersBig9 REBUILD
   ALTER INDEX ALL ON OrdersBig10 REBUILD
END;