-- Pra não falar que é nenhum... Cuidado com confusão...
-- vai primeiro procurar no master...

-- Sinceramente não acredito que devemos mudar as SPs...
-- Mas caso vá criar uma nova, utilize como boa prática, não começar com sp*... 
-- eu gosto de st*
GO
