-- Novamente... boa prática... é bom evitar o trafego de rede... e só... 
-- No big deal.. mas boa prática... eu raramente uso... só se me obrigarem...


http://www.sqlservercentral.com/articles/Performance+Tuning/2751/